# Generated by Django 5.1 on 2024-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Краткое описание поста', max_length=255),
        ),
    ]
