# Generated by Django 5.1 on 2024-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
